package net.filipes.rituals.tooltip;

import net.filipes.rituals.item.ModItems;
import net.minecraft.world.item.Items;

public class ModTooltips {

    public static void register() {
        TooltipRegistry.stageLineStyle = stage -> TooltipLine.builder()
                .literal("Stage " + stage, 0xffc400)
                .minecraftFive()
                .build();

        TooltipRegistry.killLineStyle = kills -> TooltipLine.builder()
                .literal("Kills: " + kills, 0xe31414)
                .minecraftFive()
                .build();

        TooltipRegistry.disableScrollHint(ModItems.ROSEGOLD_BOOTS);
        TooltipRegistry.disableScrollHint(ModItems.ROSEGOLD_LEGGINGS);
        TooltipRegistry.disableScrollHint(ModItems.ROSEGOLD_CHESTPLATE);
        TooltipRegistry.disableScrollHint(ModItems.ROSEGOLD_HELMET);
        TooltipRegistry.disableScrollHint(ModItems.ROSEGOLD_PICKAXE);

        TooltipRegistry.register(Items.MACE,
                TooltipLine.translated("tooltip.minecraft.mace", 0xFF0000)
        );



        TooltipRegistry.registerStages(ModItems.ROSEGOLD_BOOTS, 0xFFFFFF,

                StageAbility.passive()
                        .headerColor(0xffebeb)
                        .name("Double jump")
                        .describe(TooltipLine.builder()
                                .literal("Grants Double jump when worn", 0xe3e3e3)
                                .build())
                        .build()
        );
        TooltipRegistry.registerStages(ModItems.ROSEGOLD_LEGGINGS, 0xFFFFFF,

                StageAbility.passive()
                        .headerColor(0xffebeb)
                        .name("Speed")
                        .describe(TooltipLine.builder()
                                .literal("Gives permanent ", 0xe3e3e3)
                                .literal("Speed II ", 0x47e0ff)
                                .literal("when worn", 0xe3e3e3)
                                .build())
                        .build()
        );
        TooltipRegistry.registerStages(ModItems.ROSEGOLD_CHESTPLATE
                , 0xFFFFFF,

                StageAbility.passive()
                        .headerColor(0xffebeb)
                        .name("Overshield")
                        .describe(TooltipLine.builder()
                                .literal("Adds ", 0xe3e3e3)
                                .literal("+10 Max Health ", 0xff2e2e)
                                .literal("while worn", 0xe3e3e3)

                                .build())
                        .build()
        );
        TooltipRegistry.registerStages(ModItems.ROSEGOLD_HELMET
                , 0xFFFFFF,

                StageAbility.passive()
                        .headerColor(0xffebeb)
                        .name("Strength")
                        .describe(TooltipLine.builder()
                                .literal("Gives permanent ", 0xe3e3e3)
                                .literal("Strength II ", 0xffc800)
                                .literal("when worn", 0xe3e3e3)
                                .build())
                        .build()
        );
        TooltipRegistry.registerStages(ModItems.ROSEGOLD_PICKAXE
                , 0xffebeb,

                StageAbility.passive()
                        .headerColor(0xffebeb)
                        .describe(TooltipLine.builder()
                                .literal("Holds the power of a ", 0xe3e3e3)
                                .literal("Netherite Pickaxe ", 0x7e5494)
                                .build())
                        .build(),
                StageAbility.builder(2)
                        .describe("Unlocks Silk Touch and Fortune", 0xe3e3e3)
                        .build(),
                StageAbility.builder(3)
                        .name("Increased yield")
                        .describe("Mined blocks now drop 2x drops. Doesn't work on", 0xe3e3e3)
                        .describe("manually placed blocks", 0xe3e3e3)
                        .build(),
                StageAbility.builder(4)
                        .actionSlot(StageAbility.ActionSlot.ONE)
                        .describe("Toggle for 3x3 mining", 0xe3e3e3)
                        .build(),
                StageAbility.builder(5)
                        .actionSlot(StageAbility.ActionSlot.ONE)
                        .describe("Upgrades to 3x3x3 mining", 0xe3e3e3)
                        .build()
        );
        TooltipRegistry.registerStages(ModItems.LIGHTNING_RAPIER
                , 0x9c40ff,

                StageAbility.passive()
                        .headerColor(0x9c40ff)
                        .describe(TooltipLine.builder()
                                .literal("Increased damage in water, rain and thunder", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(2)
                        .describe("Chain lightning between enemies in range", 0xe3e3e3)
                        .build(),
                StageAbility.builder(3)
                        .describe("Hitting the same enemy charges the weapon. After 6 hits,", 0xe3e3e3)
                        .describe(TooltipLine.builder()
                                .literal("next hit strikes down the enemy and ", 0xe3e3e3)
                                .literal("stuns ", 0x30e3ff)
                                .literal("them", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(4)
                        .abilityId("lightning_rapier_charge")
                        .describe("Instantly charges the weapon", 0xe3e3e3)
                        .cooldownFromAbility()
                        .actionSlot(StageAbility.ActionSlot.ONE)
                        .build(),
                StageAbility.builder(5)
                        .abilityId("lightning_rapier_teleport")
                        .describe("Teleport forward instantly", 0xe3e3e3)
                        .cooldownFromAbility()
                        .actionSlot(StageAbility.ActionSlot.TWO)
                        .build(),
                StageAbility.builder(6)
                        .describe(TooltipLine.builder()
                                .literal("Hitting an enemy now ", 0xe3e3e3)
                                .literal("stuns ", 0x30e3ff)
                                .literal("them", 0xe3e3e3)
                                .build())
                        .build()


        );
        TooltipRegistry.registerStages(ModItems.LUNAR_BLADE
                , 0xbadeff,

                StageAbility.passive()
                        .headerColor(0x87b5ff)
                        .describe(TooltipLine.builder()
                                .literal("Offhanding its twin deals 1.5x attack damage", 0xe3e3e3)
                                .build())
                        .build(),

                StageAbility.builder(2)
                        .abilityId("lunar_mark")
                        .actionSlot(StageAbility.ActionSlot.ONE)
                        .cooldownFromAbility()
                        .describe(TooltipLine.builder()
                                .literal("Marks an enemy with a explosive mark, that launches", 0xe3e3e3)
                                .literal(" Lunar Fragments", 0xbadeff)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("hitting the enemy and transferring the mark", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(3)
                        .name("Moonshine")
                        .describe(TooltipLine.builder()
                                .literal("Holding the weapon at night gives effect ", 0xe3e3e3)
                                .literal("Moonshine", 0xbadeff)
                                .literal(",", 0xe3e3e3)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("that reduces incoming damage by 15%", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(4)
                        .abilityId("lunar_blade_on_hit")
                        .actionSlot(StageAbility.ActionSlot.TWO)
                        .cooldownFromAbility()
                        .describe(TooltipLine.builder()
                                .literal("Every hit also launches ", 0xe3e3e3)
                                .literal("Lunar Fragments ", 0xbadeff)
                                .literal("at the enemy", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(5)
                        .abilityId("twins_action_two")
                        .actionSlot(StageAbility.ActionSlot.THREE)
                        .cooldownFromAbility()
                        .describe(TooltipLine.builder()
                                .literal("Spawn 4 ", 0xe3e3e3)
                                .literal("Lunar Fragments ", 0xbadeff)
                                .literal("orbiting around you.", 0xe3e3e3)
                                .literal(" Pressing the", 0xe3e3e3)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("ability again launches one fragment. ", 0xe3e3e3)
                                .literal("If activated with ", 0xe3e3e3)
                                .literal("Solar Blade", 0xffdc8f)
                                .literal(",", 0xe3e3e3)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("consumes two fragments ", 0xe3e3e3)
                                .literal("for a ", 0xe3e3e3)
                                .literal("Solar Stormcell", 0xffdc8f)
                                .build())
                        .build(),
                StageAbility.builder(6)
                        .describe(TooltipLine.builder()
                                .literal("Switching weapons with offhand makes the other twin", 0xe3e3e3)
                                .literal(" deal 1.75x damage", 0xe3e3e3)
                                .build())
                        .build()
        );
        TooltipRegistry.registerStages(ModItems.SOLAR_BLADE
                , 0xffdc8f,

                StageAbility.passive()
                        .headerColor(0xffdc8f)
                        .describe(TooltipLine.builder()
                                .literal("Offhanding its twin deals 1.5x attack damage", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(2)
                        .abilityId("solar_mark")
                        .actionSlot(StageAbility.ActionSlot.ONE)
                        .cooldownFromAbility()
                        .describe(TooltipLine.builder()
                                .literal("Marks an enemy with a explosive mark, that launches a", 0xe3e3e3)
                                .literal(" Solar Stormcell", 0xffdc8f)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("chaining between enemies in range", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(3)
                        .name("Sunblessed")
                        .describe(TooltipLine.builder()
                                .literal("Holding the weapon at daytime gives effect ", 0xe3e3e3)
                                .literal("Sunblessed", 0xffdc8f)
                                .literal(",", 0xe3e3e3)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("that reduces incoming damage by 10%", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(4)
                        .abilityId("solar_blade_charge")
                        .actionSlot(StageAbility.ActionSlot.TWO)
                        .cooldownFromAbility()
                        .describe(TooltipLine.builder()
                                .literal("Increases attack speed for 5s", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(5)
                        .abilityId("twins_action_two")
                        .actionSlot(StageAbility.ActionSlot.THREE)
                        .cooldownFromAbility()
                        .describe(TooltipLine.builder()
                                .literal("Launch a ", 0xe3e3e3)
                                .literal("Solar Stormcell ", 0xffdc8f)
                                .literal("that chains between enemies.", 0xe3e3e3)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("With ", 0xe3e3e3)
                                .literal("Lunar Blade ", 0xbadeff)
                                .literal("each entity gets hit with a  ", 0xe3e3e3)
                                .literal("Lunar Fragment", 0xbadeff)
                                .build())
                        .build(),
                StageAbility.builder(6)
                        .describe(TooltipLine.builder()
                                .literal("Switching weapons with offhand makes the other twin", 0xe3e3e3)
                                .literal(" deal 1.75x damage", 0xe3e3e3)
                                .build())
                        .build()
        );

        TooltipRegistry.registerStages(ModItems.VORTEX_EDGE
                , 0xea98fa,

                StageAbility.passive()
                        .headerColor(0xea98fa)
                        .describe(TooltipLine.builder()
                                .literal("Attacking gives random knockback", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(2)
                        .abilityId("vortex_swap")
                        .actionSlot(StageAbility.ActionSlot.ONE)
                        .cooldownFromAbility()
                        .describe(TooltipLine.builder()
                                .literal("Swap with anyone in range", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(3)
                        .abilityId("vortex_shockwave")
                        .actionSlot(StageAbility.ActionSlot.TWO)
                        .cooldownFromAbility()
                        .describe(TooltipLine.builder()
                                .literal("Blinds everyone in a radius for 10s", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(4)
                        .describe(TooltipLine.builder()
                                .literal("Landed attacks give ", 0xe3e3e3)
                                .literal("Speed III ", 0x47e0ff)
                                .build())
                        .build(),
                StageAbility.builder(5)
                        .abilityId("vortex_beam")
                        .actionSlot(StageAbility.ActionSlot.THREE)
                        .cooldownFromAbility()
                        .describe(TooltipLine.builder()
                                .literal("Shoot a sonic beam in a straight line", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(6)
                        .abilityId("vortex_slam")
                        .actionSlot(StageAbility.ActionSlot.ONE)
                        .holdShift()
                        .cooldownFromAbility()
                        .describe(TooltipLine.builder()
                                .literal("Activate mid fall to ", 0xe3e3e3)
                                .literal("Slam ", 0xea98fa)
                                .literal("down and damage ", 0xe3e3e3)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("enemies. Longer the fall, higher the damage", 0xe3e3e3)
                                .build())
                        .build()
        );
        TooltipRegistry.registerStages(ModItems.SHADOWGUARD
                , 0xca9eff,

                StageAbility.passive()
                        .headerColor(0xca9eff)
                        .describe(TooltipLine.builder()
                                .literal("First attack deals extra damage", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(2)
                        .name("Phantom")
                        .describe(TooltipLine.builder()
                                .literal("Each attack there is a 10% chance to turn completely ", 0xe3e3e3)
                                .literal("Invisible", 0xffffff).underline()
                                .build())
                        .build(),
                StageAbility.builder(3)
                        .describe(TooltipLine.builder()
                                .literal("Wind burst unlocked", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(4)
                        .abilityId("shadowguard_launch")
                        .cooldownFromAbility()
                        .actionSlot(StageAbility.ActionSlot.ONE)
                        .describe(TooltipLine.builder()
                                .literal("Launch into the air", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(5)
                        .abilityId("lifesteal_mark")
                        .cooldownFromAbility()
                        .actionSlot(StageAbility.ActionSlot.TWO)
                        .describe(TooltipLine.builder()
                                .literal("Mark an enemy with a ", 0xe3e3e3)
                                .literal("Lifesteal Mark", 0x61ff4f)
                                .literal(".", 0xe3e3e3)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("Hitting them heals the user 75% of the damage dealt", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(6)
                        .describe(TooltipLine.builder()
                                .literal("Density and Breach unlocked", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(7)
                        .abilityId("shadowguard_grapple")
                        .cooldownFromAbility()
                        .actionSlot(StageAbility.ActionSlot.THREE)
                        .describe(TooltipLine.builder()
                                .literal("Throw out ", 0xe3e3e3)
                                .literal("Shadowguard Grapple ", 0xca9eff)
                                .literal("and grapple where ", 0xe3e3e3)
                                .literal("it lands", 0xe3e3e3)
                                .build())
                        .build()
        );
        TooltipRegistry.registerStages(ModItems.BLIGHTSPEAR
                , 0xff3b3b,

                StageAbility.passive()
                        .headerColor(0xff3b3b)
                        .describe(TooltipLine.builder()
                                .literal("Immune to slowness effects, stuns and mutes while holding", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(2)
                        .abilityId("blight_web")
                        .cooldownFromAbility()
                        .actionSlot(StageAbility.ActionSlot.ONE)
                        .describe(TooltipLine.builder()
                                .literal("Place a cobweb and a blighted puddle under an enemy.", 0xe3e3e3)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("The puddle applies effect ", 0xe3e3e3)
                                .literal("Blighted ", 0x70cc33)
                                .literal("that reduces healing", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(3)
                        .abilityId("blight_dash")
                        .cooldownFromAbility()
                        .actionSlot(StageAbility.ActionSlot.TWO)
                        .describe(TooltipLine.builder()
                                .literal("Use two dashes - first one backwards, second one", 0xe3e3e3)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("forwards. Dashes leave ", 0xe3e3e3)
                                .literal("Puddles ", 0x70cc33)
                                .literal("behind them ", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(4)
                        .describe(TooltipLine.builder()
                                .literal("Lunge unlocks", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(5)
                        .abilityId("blight_drain")
                        .cooldownFromAbility()
                        .actionSlot(StageAbility.ActionSlot.THREE)
                        .describe(TooltipLine.builder()
                                .literal("Steal ", 0xe3e3e3)
                                .literal("2 Hearts ", 0xff2e2e)
                                .literal("from a player for 30s ", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(6)
                        .abilityId("blight_tether")
                        .cooldownFromAbility()
                        .actionSlot(StageAbility.ActionSlot.ONE)
                        .holdShift()
                        .describe(TooltipLine.builder()
                                .literal("Tether the enemy to the ground for 5s, ", 0xe3e3e3)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("making them unable to escape ", 0xe3e3e3)
                                .build())
                        .build()
        );
        TooltipRegistry.registerStages(ModItems.POLARITY_BOW
                , 0xff3b3b,

                StageAbility.passive()
                        .headerColor(0xff3b3b)
                        .actionSlot(StageAbility.ActionSlot.ONE)
                        .abilityId("polarity_bow_switch")
                        .describe(TooltipLine.builder()
                                .literal("Change the bow's polarity.", 0xe3e3e3)
                                .literal(" Blue polarity ", 0x3b52ff)
                                .literal(" has faster", 0xe3e3e3)
                                .build())
                        .describe(TooltipLine.builder()

                                .literal("but weaker arrows, while", 0xe3e3e3)
                                .literal(" Red polarity ", 0xd92929)
                                .literal("has slower", 0xe3e3e3)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("but stronger arrows", 0xe3e3e3)
                                .build())
                        .cooldownFromAbility()
                        .build(),

                StageAbility.builder(2)
                        .abilityId("polarity_reverse_charge")
                        .cooldownFromAbility()
                        .actionSlot(StageAbility.ActionSlot.TWO)
                        .describe(TooltipLine.builder()
                                .literal("Shoot a arrow that " , 0xe3e3e3)
                                .literal("reverses controls", 0xffc72b)
                                .build())
                        .build(),
                StageAbility.builder(3)
                        .describe(TooltipLine.builder()
                                .literal("Hitting shots without missing builds up damage", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(4)
                        .describe(TooltipLine.builder()
                                .literal("Upgrades ", 0xe3e3e3)
                                .literal("Polarity Switch", 0xff3b3b)
                                .literal(". Switching to ", 0xe3e3e3)
                                .literal("Red polarity", 0xd92929)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("pulls enemies closer, ", 0xe3e3e3)
                                .literal("Blue polarity ", 0x3b52ff)
                                .literal("pushes ", 0xe3e3e3)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("enemies away", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(5)
                        .abilityId("polarity_tornado")
                        .cooldownFromAbility()
                        .actionSlot(StageAbility.ActionSlot.THREE)
                        .describe(TooltipLine.builder()
                                .literal("Shoot out a tornado that " , 0xe3e3e3)
                                .literal("Pushes ", 0x3b52ff)
                                .literal("or " , 0xe3e3e3)
                                .literal("Pulls", 0xd92929)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("enemies" , 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(6)
                        .abilityId("polarity_bow_dash")
                        .cooldownFromAbility()
                        .actionSlot(StageAbility.ActionSlot.ONE)
                        .holdShift()
                        .describe(TooltipLine.builder()
                                .literal("Dash " , 0xe3e3e3)
                                .literal("Left ", 0x3b52ff)
                                .literal("or " , 0xe3e3e3)
                                .literal("Right ", 0xd92929)
                                .literal("with a shield that damages" , 0xe3e3e3)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("and knockbacks enemies" , 0xe3e3e3)
                                .build())
                        .build()
        );
        TooltipRegistry.registerStages(ModItems.PULSE_BLASTER
                , 0xff3b3b,

                StageAbility.passive()
                        .headerColor(0xff3b3b)
                        .describe(TooltipLine.builder()
                                .literal("Shoot 8 Beams per payload. Reload with ", 0xe3e3e3)
                                .literal("Redstone dust", 0xd92929)
                                .build())
                        .build(),
                StageAbility.builder(2)
                        .describe(TooltipLine.builder()
                                .literal("Continuous firing increases the fire rate", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(3)
                        .describe(TooltipLine.builder()
                                .literal("Magazine size 8 > 12", 0xe3e3e3)
                                .literal("Heat capacity 100 > 150", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(4)
                        .abilityId("pulse_blaster_shotgun")
                        .actionSlot(StageAbility.ActionSlot.ONE)
                        .cooldownFromAbility()
                        .describe(TooltipLine.builder()
                                .literal("Shoot all remaining loaded shots at once", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(5)
                        .abilityId("pulse_blaster_overcharge")
                        .actionSlot(StageAbility.ActionSlot.TWO)
                        .cooldownFromAbility()
                        .describe(TooltipLine.builder()
                                .literal("Increased fire rate and damage for 5s", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(6)
                        .abilityId("pulse_blaster_death_laser")
                        .actionSlot(StageAbility.ActionSlot.THREE)
                        .cooldownFromAbility()
                        .describe(TooltipLine.builder()
                                .literal("Shoot a giant beam dealing heavy damage", 0xe3e3e3)
                                .build())
                        .build()
        );
        TooltipRegistry.registerStages(ModItems.DEPTHSTRIKE
                , 0xff4545,

                StageAbility.passive()
                        .headerColor(0xff4545)
                        .describe(TooltipLine.builder()
                                .literal("Always returns back to the owner. Hitting an enemy applies", 0xe3e3e3)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("effect ", 0xe3e3e3)
                                .literal("Conductive", 0x0dffd7)
                                .build())
                        .build(),
                StageAbility.builder(2)
                        .abilityId("depthstrike_recall")
                        .actionSlot(StageAbility.ActionSlot.ONE)
                        .cooldownFromAbility()
                        .describe(TooltipLine.builder()
                                .literal("Instantly recall ", 0xe3e3e3)
                                .literal("Depthstrike ", 0x00ffc3)
                                .literal("back ", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(3)
                        .abilityId("depthstrike_ability")
                        .actionSlot(StageAbility.ActionSlot.TWO)
                        .cooldownFromAbility()
                        .describe(TooltipLine.builder()
                                .literal("Shoot overcharged ", 0xe3e3e3)
                                .literal("Depthstrike ", 0x00ffc3)
                                .literal("that knocks back ", 0xe3e3e3)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("enemies on hit. After landing, it splits into four ", 0xe3e3e3).build())
                        .describe(TooltipLine.builder()
                                .literal("Splinters ", 0x00ffc3)
                                .literal("that explode on impact", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(4)
                        .describe(TooltipLine.builder()
                                .literal("Conductive ", 0x0dffd7)
                                .literal("now stacks. ", 0xe3e3e3)
                                .literal("Depthstrike ", 0x00ffc3)
                                .literal("deals higher", 0xe3e3e3)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("damage if the enemy has higher level of ", 0xe3e3e3)
                                .literal("Conductive ", 0x0dffd7)
                                .build())
                        .build(),
                StageAbility.builder(5)
                        .abilityId("depthstrike_ground_ability")
                        .actionSlot(StageAbility.ActionSlot.THREE)
                        .cooldownFromAbility()
                        .describe(TooltipLine.builder()
                                .literal("Spawn biting mouths from the ground that deal damage ", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(6)
                        .abilityId("depthstrike_charged_ball")
                        .actionSlot(StageAbility.ActionSlot.ONE)
                        .holdShift()
                        .cooldownFromAbility()
                        .describe(TooltipLine.builder()
                                .literal("Shoot a charged ball that explodes on impact ", 0xe3e3e3)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("It also homes onto enemies if they have ", 0xe3e3e3)
                                .literal("Conductive ", 0x0dffd7)
                                .build())
                        .build()

        );
        TooltipRegistry.registerStages(ModItems.CINDERBOLT
                , 0xff5005,

                StageAbility.passive()
                        .headerColor(0xff5005)
                        .describe(TooltipLine.builder()
                                .literal("Shoots arrows that ignite enemies", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(2)
                        .describe(TooltipLine.builder()
                                .literal("Shoot a ", 0xe3e3e3)
                                .literal("Piercing arrow ", 0xff8400)
                                .literal("dealing higher damage ", 0xe3e3e3)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("Arrows alternate", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(3)
                        .describe(TooltipLine.builder()
                                .literal("Shoot a ", 0xe3e3e3)
                                .literal("Explosive arrow ", 0xffc800)
                                .literal("that explodes on hit ", 0xe3e3e3)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("Arrows alternate one after another", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(4)
                        .abilityId("cinderbolt_triple")
                        .actionSlot(StageAbility.ActionSlot.ONE)
                        .cooldownFromAbility()
                        .describe(TooltipLine.builder()
                                .literal("Next 3 arrow don't require charging", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(5)
                        .abilityId("fire_cinderbolt_beam")
                        .actionSlot(StageAbility.ActionSlot.TWO)
                        .cooldownFromAbility()
                        .describe(TooltipLine.builder()
                                .literal("Shoot a deadly fire beam that ignites everything", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(6)
                        .describe(TooltipLine.builder()
                                .literal("Have three shields orbiting around you while holding ", 0xe3e3e3)
                                .build())

                        .describe(TooltipLine.builder()
                                .literal("Cinderbolt", 0xff5005)
                                .literal(", reducing damage by 70%", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(7)
                        .abilityId("cinderbolt_death_save")
                        .cooldownFromAbility()
                        .describe(TooltipLine.builder()
                                .literal("Lethal damage leaves you on ", 0xe3e3e3)
                                .literal("0.5 Hearts", 0xff2e2e)
                                .literal(",", 0xe3e3e3)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("and gives you ", 0xe3e3e3)
                                .literal("Invulnerability ", 0xFFD54A)
                                .literal("for 5s while knocking", 0xe3e3e3)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("back enemies", 0xe3e3e3)
                                .build())
                        .build()
        );
        TooltipRegistry.registerStages(ModItems.PHARATHORN
                , 0x05ffee,

                StageAbility.passive()
                        .headerColor(0x05ffee)
                        .describe(TooltipLine.builder()
                                .literal("Enemies under 50% health are ", 0xe3e3e3)
                                .literal("Marked", 0xff3d3d)
                                .literal(".", 0xe3e3e3)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("Increased damage against marked enemies", 0xe3e3e3)
                                .build())
                        .build(),

                StageAbility.builder(2)
                        .abilityId("pharathorn_fortify")
                        .cooldownFromAbility()
                        .actionSlot(StageAbility.ActionSlot.ONE)
                        .describe(TooltipLine.builder()
                                .literal("Gain ", 0xe3e3e3)
                                .literal("Resistance IV ", 0xab7cbf)
                                .literal("and ", 0xe3e3e3)
                                .literal("Slowness V ", 0x867f8a)
                                .literal("for 4s ", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(3)
                        .abilityId("pharathorn_ground_smash")
                        .cooldownFromAbility()
                        .actionSlot(StageAbility.ActionSlot.TWO)
                        .describe(TooltipLine.builder()
                                .literal("Smash the ground in front of you, damaging everyone", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(4)
                        .describe(TooltipLine.builder()
                                .literal("Not attacking slowly builds up ", 0xe3e3e3)
                                .literal("Armor ", 0xdedede)
                                .literal("(Max 20) ", 0xe3e3e3)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("Attacking resets the boost", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(5)
                        .abilityId("pharathorn_reveal")
                        .cooldownFromAbility()
                        .actionSlot(StageAbility.ActionSlot.THREE)
                        .describe(TooltipLine.builder()
                                .literal("Mark ", 0xff3d3d)
                                .literal("everyone in a 32 block radius for 5s", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(6)
                        .abilityId("pharathorn_dash")
                        .cooldownFromAbility()
                        .actionSlot(StageAbility.ActionSlot.ONE)
                        .holdShift()
                        .describe(TooltipLine.builder()
                                .literal("Dash forward with ", 0xe3e3e3)
                                .literal("Pharathorns ", 0x1cffe8)
                                .literal("stabbing", 0xe3e3e3)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("behind you, dealing damage", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(7)
                        .abilityId("pharathorn_spiral_stab")
                        .cooldownFromAbility()
                        .actionSlot(StageAbility.ActionSlot.TWO)
                        .holdShift()
                        .describe(TooltipLine.builder()
                                .literal("Spawn ", 0xe3e3e3)

                                .literal("Pharathorns ", 0x1cffe8)
                                .literal("in a spiral pattern around you", 0xe3e3e3)
                                .build())
                        .build()
        );
        TooltipRegistry.registerStages(ModItems.TEMPORAL_GLASSREAVER
                , 0xd15cff,

                StageAbility.passive()
                        .headerColor(0xd15cff)
                        .describe(TooltipLine.builder()
                                .literal("Works like an axe. After 4 critical hits, it is no longer ", 0xe3e3e3)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("required to jump to crit", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(2)
                        .abilityId("temporal_shield_barrier")
                        .cooldownFromAbility()
                        .actionSlot(StageAbility.ActionSlot.ONE)
                        .describe(TooltipLine.builder()
                                .literal("Deploy a ", 0xe3e3e3)
                                .literal("Temporal Barrier", 0x34994a)
                                .literal(", knocking back enemies ", 0xe3e3e3)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("and reflecting projectiles", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(3)
                        .abilityId("temporal_mute")
                        .cooldownFromAbility()
                        .actionSlot(StageAbility.ActionSlot.TWO)
                        .describe(TooltipLine.builder()
                                .literal("Mute ", 0xff2e2e)
                                .literal("someone, making them unable to use any ability for 6s", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(4)
                        .describe(TooltipLine.builder()
                                .literal("Crit ability threshold 4 > 3 crits in a row", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(5)
                        .abilityId("temporal_recall")
                        .cooldownFromAbility()
                        .actionSlot(StageAbility.ActionSlot.THREE)
                        .describe(TooltipLine.builder()
                                .literal("Spawn a ", 0xe3e3e3)
                                .literal("Shadow ", 0xe3e3e3)
                                .literal("of you anywhere. After", 0xe3e3e3)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("6s or after activating the ability again you", 0xe3e3e3)
                                .literal(" teleport to it's position", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(6)
                        .describe(TooltipLine.builder()
                                .literal("Temporal Mute ", 0xff2e2e)
                                .literal("now also makes target not able to move", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(7)
                        .abilityId("temporal_slow_zone")
                        .cooldownFromAbility()
                        .actionSlot(StageAbility.ActionSlot.ONE)
                        .holdShift()
                        .describe(TooltipLine.builder()
                                .literal("Create a giant ", 0xe3e3e3)
                                .literal("Time warp zone ", 0x2050b0)
                                .literal("slowing", 0xe3e3e3)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("everything around you for 6s", 0xe3e3e3)
                                .build())
                        .build()

        );
        TooltipRegistry.registerStages(ModItems.SHADESHATTER
                , 0x00d0ff,

                StageAbility.passive()
                        .headerColor(0x00d0ff)
                        .actionSlot(StageAbility.ActionSlot.ONE)
                        .abilityId("shadeshatter_morph")
                        .describe(TooltipLine.builder()
                                .literal("Right-click to shoot a ", 0xe3e3e3)
                                .literal("Charged spell", 0x00d0ff)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("Transforms into a random weapon for 7s", 0xe3e3e3)
                                .build())
                        .cooldownFromAbility()
                        .build(),
                StageAbility.builder(2)
                        .describe(TooltipLine.builder()
                                .literal("Shadeshatter ", 0x1cd2ff)
                                .literal("can now manually attack, with a cooldown", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(3)
                        .describe(TooltipLine.builder()
                                .literal("Morphed ", 0xfc3030)
                                .literal("weapons now have a random stage", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(4)
                        .abilityId("shadeshatter_wormhole")
                        .cooldownFromAbility()
                        .actionSlot(StageAbility.ActionSlot.TWO)
                        .describe(TooltipLine.builder()
                                .literal("Spawn a ", 0xe3e3e3)
                                .literal("Wormhole ", 0xb521ff)
                                .literal("pulling enemies inside. After a", 0xe3e3e3)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("delay you teleport there and ", 0xe3e3e3)
                                .literal("knockback them", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(5)
                        .describe(TooltipLine.builder()
                                .literal("Morphed ", 0xfc3030)
                                .literal("weapons are now at Max stage", 0xe3e3e3)
                                .build())
                        .build(),
                StageAbility.builder(6)
                        .describe(TooltipLine.builder()
                                .literal("Morphing ", 0xfc3030)
                                .literal("a weapon gives you a random", 0xe3e3e3)
                                .build())
                        .describe(TooltipLine.builder()
                                .literal("Buff ", 0x41fa66)
                                .literal("or ", 0xe3e3e3)
                                .literal("Debuff", 0xfc3030)
                                .build())
                        .build()
        );
    }
}